name: LLM Stack

services:
  ollama-igpu:
    profiles:
      - intel_xpu
    image: intelanalytics/ipex-llm-inference-cpp-xpu:2.3.0-SNAPSHOT@sha256:74c7fba6e12a083ff664ae54e1ff16a977a39caa03d272125db406eeddaee09e
    volumes:
      - ${BASE_STACK_DIR}/models:/root/.ollama
      - ./entry.sh:/entry.sh
    devices:
      - /dev/dri:/dev/dri
    environment:
      - TZ=Europe/Berlin
      - no_proxy=localhost,127.0.0.1
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_INTEL_GPU=true
      - DEVICE=${DEVICE}
      - OLLAMA_NUM_PARALLEL=${OLLAMA_NUM_PARALLEL}
      - OLLAMA_NUM_GPU=${OLLAMA_NUM_GPU}
      - ZES_ENABLE_SYSMAN=${ZES_ENABLE_SYSMAN}
      - GGML_SYCL_DEBUG=${GGML_SYCL_DEBUG}
    ports:
      - '11434:11434'
    networks:
      - proxy_net
    entrypoint:
      [ "/bin/bash", "-c", "/entry.sh" ]
    restart: always

  ollama-cpu:
    profiles:
      - standard
    image: ollama/ollama:0.32.14@sha256:9d30908e41144b1f1da89b9d8e33c07e4aeb43ff41a8660241b1686e2cc330ad
    volumes:
      - ${BASE_STACK_DIR}/models:/root/.ollama
      - ./entry.sh:/entry.sh
    environment:
      - TZ=Europe/Berlin
      - no_proxy=localhost,127.0.0.1
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_INTEL_GPU=false # Wichtig für entry.sh
      - DEVICE=${DEVICE}
      - OLLAMA_NUM_PARALLEL=${OLLAMA_NUM_PARALLEL}
      - OLLAMA_NUM_GPU=${OLLAMA_NUM_GPU}
      - ZES_ENABLE_SYSMAN=${ZES_ENABLE_SYSMAN}
      - GGML_SYCL_DEBUG=${GGML_SYCL_DEBUG}
    ports:
      - '11434:11434'
    networks:
      - proxy_net
    entrypoint:
      [ "/bin/bash", "-c", "/entry.sh" ]
    restart: always

networks:
  proxy_net:
    external: true
    name: network_backend_net
